kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
  namespace: default
spec:
  selector:
    matchLabels:
      app: nfs-client-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner-x86:latest
          resources:
            limits:
              cpu: 2
              memory: 1Gi
          volumeMounts:
            - name: nfs-client-ssd
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: ff1.dev/nfs
            - name: NFS_SERVER
              value: 192.168.178.10
            - name: NFS_PATH
              value: /mnt/POOL1/SHARE06
          mountOptions:
            - nfsvers=3
      volumes:
        - name: nfs-client-ssd
          nfs:
            server: 192.168.178.10
            path: /mnt/POOL1/SHARE06
